spring.application.name=demo

oci.objectstorage.url=https://objectstorage.sa-saopaulo-1.oraclecloud.com/n/grrff6e3s3vz/b/hackathon-team23-models/o/categorias_financeiras.json
oci.objectstorage.enabled=true
